apiVersion: v1
kind: Service
metadata:
  name: {{ include "justflow.fullname" . }}
  labels:
    {{- include "justflow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.justflow.service.type }}
  ports:
    {{- if .Values.justflow.service.ports.frontend }}
    - port: {{ .Values.justflow.service.ports.frontend.port }}
      targetPort: {{ .Values.justflow.service.ports.frontend.targetPort }}
      protocol: TCP
      name: {{ .Values.justflow.service.ports.frontend.name }}
    {{- end }}
    {{- if .Values.justflow.service.ports.backend }}
    - port: {{ .Values.justflow.service.ports.backend.port }}
      targetPort: {{ .Values.justflow.service.ports.backend.targetPort }}
      protocol: TCP
      name: {{ .Values.justflow.service.ports.backend.name }}
    {{- end }}
  selector:
    {{- include "justflow.justflow.selectorLabels" . | nindent 4 }}
