{{- if .Values.justwms.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "justwms.fullname" . }}-config"
  labels:
    {{- include "justwms.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- toYaml .Values.justwms.configMap.data | nindent 4 }}
{{- end }}